In [1]:
import numpy as np

In [2]:
A = np.array([
    [7.35272, 0.88255, -1.378574],
    [0.88255,   5.58351,   0.528167],
    [-2.27005,  0.528167,   4.430329]
])

b = np.array([
    [1],
    [0],
    [0]
])
A, b

(array([[ 7.35272 ,  0.88255 , -1.378574],
        [ 0.88255 ,  5.58351 ,  0.528167],
        [-2.27005 ,  0.528167,  4.430329]]),
 array([[1],
        [0],
        [0]]))

In [3]:
solution = np.linalg.solve(A, b)
solution

array([[ 0.15557738],
       [-0.03249829],
       [ 0.0835904 ]])

In [4]:
size = A.shape[0]

In [5]:
# Transform origin matrix to a right form:

D = np.identity(size)
A_diag_indices = np.diag(A)
D[np.diag_indices_from(D)] = A_diag_indices
D

array([[7.35272 , 0.      , 0.      ],
       [0.      , 5.58351 , 0.      ],
       [0.      , 0.      , 4.430329]])

In [6]:
HD = np.identity(size) - np.matmul(np.linalg.inv(D), A)
HD

array([[ 0.        , -0.12003041,  0.1874917 ],
       [-0.15806366,  0.        , -0.09459408],
       [ 0.51238858, -0.1192162 ,  0.        ]])

In [7]:
g_D = np.matmul(np.linalg.inv(D), b)
g_D

array([[0.13600409],
       [0.        ],
       [0.        ]])

In [8]:
HD_norm = np.linalg.norm(HD, ord=np.inf)
HD_norm

0.6316047860102488

In [9]:
def simple_iteration_method(H, g, k: int):
    appr = {}
    n = H.shape[0]
    x = np.zeros((n, 1))
    for i in range(k):
        x = np.matmul(H, x) + g
        appr[i + 1] = x
    return appr

def seidel_method(H, g, k) -> list:
    n = H.shape[0]
    prev_x = np.zeros(n)
    x = np.zeros(n)
    for it in range(k):
        for i in range(n):
            x[i] = np.dot(H[i, 0:i], x[0:i]) + np.dot(H[i, i:n], prev_x[i:n]) + g[i]
        prev_x = x
    return x.reshape((n, 1))

In [10]:
def inf_norm(arr):
    return np.linalg.norm(arr, ord=np.inf)



In [11]:
k = 7
appr1 = simple_iteration_method(HD, g_D, k)
x = appr1[k]
x, solution

(array([[ 0.15546676],
        [-0.0323991 ],
        [ 0.08336929]]),
 array([[ 0.15557738],
        [-0.03249829],
        [ 0.0835904 ]]))

In [12]:
x_seid = seidel_method(HD, g_D, 7)
x_seid

array([[ 0.15557696],
       [-0.03249808],
       [ 0.08359016]])